### PR TITLE
Added Visual Studio Team Services (VSTS) OAuthClient

### PR DESCRIPTION
**Pull request by daltskin**
New VSTSClient.cs added for accessing the VSTS REST API: https://www.visualstudio.com/en-us/docs/integrate/api/overview

### CODE REVIEW

**Comment by StefanSchoof** [comment]
Does this work in the refresh token case? The documentation says the refresh_token has to be refresh_token. https://www.visualstudio.com/en-us/docs/integrate/get-started/authentication/oauth#refresh-an-expired-access-token
Since the GrantType property is private in the base class the questions is how to get the information of the grant_type

**Comment by StefanSchoof** [comment]
To prevent misunderstanding, I am not a Contributor or anything to this project. I was only making research and test to write also a VSTS provider.

I think that `"application/x-www-form-urlencoded` is the default and we do not need to concat the body ourself. We can let RestSharp do the work, with something like this:

        protected override void BeforeGetAccessToken(BeforeAfterRequestArgs args)
        {
            string grantType = args.Parameters["refresh_token"] != null ? "refresh_token" : "urn:ietf:params:oauth:grant-type:jwt-bearer";
            args.Request.AddObject(new
            {
                client_assertion_type = "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
                client_assertion = args.Configuration.ClientSecret,
                grant_type = grantType,
                assertion = args.Parameters["refresh_token"] ?? args.Parameters["code"],
                redirect_uri = args.Configuration.RedirectUri
            });
        }

**Comment by daltskin** [comment]
Having a look here, your assumption on RestSharp looks correct: https://github.com/restsharp/RestSharp/blob/e7c65df751427298cb59f5456bbf1f59967996be/RestSharp/Http.cs

**Comment by daltskin** [comment]
@niemyjski , @titarenko anymore required from me for this PR?

**Comment by niemyjski** [comment]
@daltskin looks good to me. Could you please resolve the conflicts as well as update the tag in the csproj and readme to mention VSTS (moved to new csproj format) and I'll get this merged in :).

**Comment by niemyjski** [comment]
LGTM, Thanks for the PR.

**Pull request merged**
