### PR TITLE
Added Uber client

### PR DESCRIPTION
**Pull request by skasturi**
Added Uber client

### CODE REVIEW

**Comment by niemyjski** [comment]
Thanks!

**Comment by skasturi** [comment]
Thanks niemyjski! 

Quick question: Would this be automatically build and picked up by Nuget if I Install this package?

**Comment by niemyjski** [comment]
I think so, cc: @titarenko for conformation.

**Comment by skasturi** [comment]
@titarenko Hello Constantin, The team city build shows that the branch is in build queue but there are no compatible agents. Is there anything we can do to push this forward? I want to use the build asap.

**Comment by skasturi** [comment]
The build hasn't started for almost a day now. Is this expected? Also, I am not able to add my machine as a compatible agent. I have installed required software as well. I guess my machine needs to be authorized as a build machine by the admin. Please let me know if you can approve that.

**Comment by titarenko** [comment]
Hi @skasturi, thank you for contributing!
Regarding to build issue: it seems like someone has replaced teamcity agents (on system level, on project level there is no such possibility), so now we have "Unmet requirements: DotNetFramework4.0_x86 exists". I'll try to figure out what was changed and how we will go further with releases.

**Comment by titarenko** [comment]
Well, you can have a glance here http://teamcity.codebetter.com/queue.html :) - there are at least another 44 projects (including well-known, like Fluent NHibernate) which are incompatible with existing build agents now. It seems like they have moved from .NET to Mono, and our build steps are incompatible with that ATM.

**Comment by skasturi** [comment]
@titarenko Can you please change the build steps? If not, I am willing to contribute my machine for building. How do I make sure it's authorized by the administrator? (I have the required teamcity builder bits installed on my machine). 

It's sad to see the code checked in but not released.

**Comment by skasturi** [comment]
Looks like http://teamcity.codebetter.com/ is down completely. I can't even 

image

**Comment by titarenko** [comment]
@skasturi Regarding changing build steps - I can create account for you if you have an idea how to reconfigure them in current version of codebetter's CI. Regarding your own machine - if you could setup CI, that would be just great, once build passes, I will provide you with rights to publish to nuget.org.

**Comment by titarenko** [comment]
Recently I found AppVeyor CI, it's free for OSS projects.
Link to OAuth2 project is https://ci.appveyor.com/project/titarenko/oauth2
Will try to finalize config today.

**Comment by skasturi** [comment]
@titarenko Awesome. This is very nice. Let me if you still need me to set up CI on my machine.

**Comment by titarenko** [comment]
I spotted that teamcity@codebetter is up again, so I decided to investigate exact reason why there is no compatible agent. And it was NuGet version. NuGet-related build steps were configured to use 2.2 version, and, I do not know why, but currently no build agent can provide it. So I specified custom exe (from .nuget folder, it always was there).

Release build is started, and as I see now, it was finished successfully, please check whether new version (0.8.38) installs and works well (I'm sure it should, but just in case).

**Pull request merged**
