### PR TITLE
Add todoist support

### PR DESCRIPTION
**Pull request by JamieHouston**
Added a client for Todoist. Did a tiny bit of cleaning up as well.

### CODE REVIEW

**Comment by JamieHouston** [comment]
@titarenko are you planning to merge this or is there something else you'd like me to do?  I'd like to reference the nuget package instead of my fork if possible.  If not, no worries.. just checking.

**Comment by niemyjski** [comment]
Thanks for your pull request! I'll a bit behind but I'll try and get a nuget release out. Would you mind monitoring the build and seeing if there are any build failures and updating me.

**Comment by JamieHouston** [comment]
Uggg... and now it's failing.  I'll investigate this evening.  Thank you for merging.

**Comment by JamieHouston** [comment]
@niemyjski I don't see a succesfull build of TC on the [build history tab](http://teamcity.codebetter.com/viewType.html?buildTypeId=bt1045&tab=buildTypeHistoryList).  Am I missing something?  I ran the tests locally and get a different exception that TC gets, which is the feature tests failing .  This appears to be fixed with [this SO answer](http://stackoverflow.com/a/35587531/246914) so I'm trying that out.  But need to stop for the night and would want to test more before doing a PR with that change anyway.

I'm not sure how much value the Acceptance Tests are providing now.  I love BDD and this style of testing, but it appears to only test one provider (google) and hasn't been updated since 2012.  I'm happy to try getting it running again and maybe even updating to test all the providers.  I'm just not sure if that's the issue with TC.

**Pull request merged**
