### PR TITLE
Added fitbit client

### PR DESCRIPTION
**Pull request by samble**
Changed Autofac in Example project to 2.6.3.x version (project did not build otherwise)

I submitted this a few days ago but the history was a mess. Here it is cleanly. Let me know if I should change anything, I've never done this before.

### CODE REVIEW

**Comment by niemyjski** [comment]
Thanks for the pr, Is there any chance you could look into why the sample won't build with the latest dependencies.

**Comment by samble** [comment]
@niemyjski Check out 28f7076. All projects were in .NET 4.0, and Autofac supports 4.0 just fine. Autofac.Mvc5 only supports 4.5 though. I upgraded all projects to .NET 4.5.2, and then reinstalled all NuGet packages that VS warned me about.

All unit non-ignored tests still pass. I couldn't get the SpecFlow test to run, it complained about a thread apartment state both before and after my modifications. It looks like the thread apartment settings are right in the App.config so I'm not sure what the problem is there.

3e6774a is just some cleanup.

**Comment by niemyjski** [comment]
Thanks for these changes! Would it be possible to revert the changes to the OAuth project, I'd like to keep it targeting .net 4.0 but I'm fine with all the others (Tests and Samples) being upgraded.

**Comment by samble** [comment]
Done in cd9c06e

I wanted to ask yall about how you foresaw people using these client libs. I'm building a webapp that interacts with the Fitbit service, and some of the first things I'm facing are persisting the token and adding new methods to grab data other than user data.

I can do both those things in various ways with these libs, and they'll all require some refactoring. I'm happy to go off on my own and do that for my own ends. Do you want those changes back? Or do you have any guidance or suggestions, based on how you designed the libs?

**Comment by samble** [comment]
Hey @niemyjski - anything else to do on the PR?

**Comment by niemyjski** [comment]
I think we try to handle just the oauth calls and leave everything up to the user. I tend to try and make things dumb and generic as possible so others can use them. @titarenko built this library and I just help contribute fixes / help where I can. We use it on https://github.com/exceptionless/Exceptionless and it works out really good.

**Pull request merged**
